on: [push, pull_request]

name: Test Kernel
jobs:
  build:
    name: Compile Kernel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Kernel.
        run: |
          apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex bison device-tree-compiler sudo
          cd $HOME
          curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | sh
          git clone --depth 1 https://github.com/danascape/sworkflow
          cd sworkflow
          bash tests/compile_test.sh
